[workspace]
members = [
  "nove_core",
  "sdl2",
  "snake_demo", "tracing",
]
resolver = "2"

[workspace.package]
version = "0.2.0"
edition = "2021"
authors = [ "Kriogenia <ricardo@sotoestevez.dev>"]

[workspace.dependencies]
quicli = "0.4.0"
rand = "0.8.5"
sdl2 = "0.36.0"
structopt = "0.3"
