[workspace]
members = [
  "nove_core",
  "sdl2",
]
resolver = "2"

[workspace.package]
version = "0.2.0"
edition = "2021"
authors = [ "Kriogenia <ricardo@sotoestevez.dev>"]

[workspace.dependencies]
log = "0.4"
quicli = "0.4"
rand = "0.8"
sdl2 = "0.36"
structopt = "0.3"
