[workspace]
members = [
  "nove_core",
  "snake_demo",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = [ "Kriogenia <ricardo@sotoestevez.dev>"]

[workspace.dependencies]

