[package]
name = "sdl2"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
nove_core = { path = "../nove_core" }
#rand.workspace = true
sdl2.workspace = true
quicli.workspace = true
structopt.workspace = true
