[package]
name = "nove_core"
version.workspace = true
edition.workspace = true

[dependencies]
log.workspace = true
lazy_static = "1.4.0"
thiserror = "1.0.57"

[dev-dependencies]
sdl2.workspace = true
rand.workspace = true
env_logger = "0.11.3"
