[package]
name = "tracing"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
nove_core = { path = "../nove_core" }
quicli.workspace = true
structopt.workspace = true
